app:
  system:
      Mode: "debug"
      Instance: "visitor"
      DebugLevel: 8
  graylog:
      Host: "192.168.0.48"
      Port: 12201
  server:
      listen: ":8094"
      MaxConcurrentStreams: 1000
      Timeout: 1
      Time: 1
      MaxConnectionIdle: 0
  aerospike:
      Hosts:
        - 127.0.0.1:3000
        - 127.0.0.1:3000
      ConnectionTimeout: 1000
      GetTimeout: 1000
      WriteTimeout: 1000
      Expiration: 3600
      Set: "users"
      NameSpace: "test"