app:
  system:
      cpu: 4
      LogFile: "/var/log/php/web_stats.log"
      mode: "debug"
      instance: "videonow-local-storage"
      DebugLevel: 8
  graylog:
      host: "192.168.0.48"
      port: 12201
  server:
    grpc:
        listen: ":8081"
    http:
        listen: ":8082"
        ReadTimeout: 5
        WriteTimeout: 5
        MaxHeaderBytes: 32000
        cors:
            AllowedOrigins: ["*"]
            AllowCredentials: true
            AllowedMethods: ["GET", "POST", "PATCH", "DELETE"]
            AllowedHeaders: ["*"]
            MaxAge: 1
            Debug: false
            OptionsPassthrough: false
  cache:
    DefaultExpiration: 10
    CleanupInterval: 30
  aerospike:
    Hosts:
      - 127.0.0.1:3000
      - 127.0.0.1:3000
    Timeout: 5000,
    ConnectionTimeout: 5000,
    GetTimeout: 10,
    WriteTimeout: 10,
    Ttl: 0
    Set: "visitor"
    NameSpace: "users"
  database:
    SxGeoCity: "/Users/kretsu/Work/Go/src/github.com/krecu/go-visitor/databases/SxGeoMax.dat"
    MaxMind: "/Users/kretsu/Work/Go/src/github.com/krecu/go-visitor/databases/GeoLite2-City.mmdb"
    BrowsCap: "/Users/kretsu/Work/Go/src/github.com/krecu/go-visitor/databases/full_php_browscap.ini"