app:
  system:
      cpu: 4
      LogFile: "/var/www/html/visitor.videonow.ru/new/debug.log"
      mode: "debug"
      instance: "videonow-visitor"
      DebugLevel: 8
  graylog:
      host: "192.168.0.48"
      port: 12201
  server:
    grpc:
        enable: true
        listen: ":5556"
    http:
        enable: true
        listen: ":50052"
        ReadTimeout: 5
        WriteTimeout: 5
        MaxHeaderBytes: 32000
        cors:
            AllowedOrigins: ["*"]
            AllowCredentials: true
            AllowedMethods: ["GET", "POST", "PATCH", "DELETE"]
            AllowedHeaders: ["*"]
            MaxAge: 1
            Debug: false
            OptionsPassthrough: false
  cache:
    DefaultExpiration: 10
    CleanupInterval: 30
  aerospike:
    Hosts:
      - 192.168.0.2:3000
      - 192.168.0.5:3000
    Timeout: 5000,
    ConnectionTimeout: 5000,
    GetTimeout: 10,
    WriteTimeout: 10,
    Ttl: 0
    Set: "users"
    NameSpace: "visitor"
  database:
    SxGeoCity: "/var/www/html/visitor.videonow.ru/new/database/SxGeoMax.dat"
    MaxMind: "/var/www/html/visitor.videonow.ru/new/database/GeoLite2-City.mmdb"
    UaParser: "/var/www/html/visitor.videonow.ru/new/database/uaparser.yaml"
    BrowsCap: "/var/www/html/visitor.videonow.ru/new/database/full_php_browscap.ini"